project:
  type: website
  output-dir: docs

website:
  title: "Paweł Morzywołek"
  navbar:
    pinned: true
    background: secondary
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research/index.qmd
      - text: Teaching
        href: teaching/index.qmd
      - text: Presentations
        href: presentations/index.qmd
      
    right:
      - icon: github
        href: https://github.com/pmorzywolek
      - icon: twitter
        href: https://twitter.com/PMorzywolek
      - icon: linkedin
        href: https://www.linkedin.com/in/pawel-morzywolek-50071bb4/
      - icon: file-text-fill
        href: cv.pdf
      - icon: envelope-fill
        aria-label: email
        href: "mailto:pmorzywo@uw.edu"  
        
  google-analytics: "G-WVGK8BL8QH"

format:
  html:
    css: styles.css
    theme: 
      - cosmo
      - html/styles.scss
    toc: false
    page-layout: full
editor: visual

