## Preprints

-   van Geloven, N., Keogh, R., van Amsterdam, W., Cinà, G., Krijthe, J., Peek, N., Luijken, K., Magliacane, S., Morzywołek, P., van Ommen, T., Putter, H., Sperrin, M., Wang, J., Weir, D., Didelez, V. **"Causal blind spots when using prediction models for treatment decisions"**, arxiv, 2024. \[[arxiv](https://arxiv.org/abs/2402.17366)\]
-   Luijken, K., Morzywołek, P., van Amsterdam, W., Cinà, G., Hoogland, J., Keogh, R., Krijthe, J., Magliacane, S., van Ommen, T., Peek, N., Putter, H., van Smeden, M., Sperrin, M., Wang, J., Weir, D., Didelez, V., van Geloven, N. **"Risk-based decision making: estimands for sequential prediction under interventions"**, arxiv, 2023. \[[arxiv](https://arxiv.org/abs/2311.17547)\]
-   Vansteelandt, S., Morzywołek, P. **"Orthogonal prediction of counterfactual outcomes"**, arxiv, 2023. \[[arxiv](https://arxiv.org/abs/2311.09423)\]
-   Morzywołek, P., Decruyenaere, J., Vansteelandt, S. **"On a general class of orthogonal learners for the estimation of heterogeneous treatment effects"**, arxiv, 2023. \[[arxiv](https://arxiv.org/abs/2303.12687)\] \[[code](https://github.com/pmorzywolek/CATEsimulations)\]

## 2023

-   Steen, J., Morzywołek, P., Van Biesen, W., Decruyenaere, J., Vansteelandt, S. **"Dealing with time-dependent exposures and confounding when defining and estimating attributable fractions—Revisiting estimands and estimators"**, *Statistics in Medicine*, 2023. \[[paper](https://onlinelibrary.wiley.com/doi/10.1002/sim.9988)\] \[[arxiv](https://arxiv.org/abs/2011.04833)\] \[[code](https://github.com/jmpsteen/timedeppaf)\]

## 2022

-   Morzywołek, P., Steen, J., Vansteelandt, S., Decruyenaere, J., Sterckx S., Van Biesen, W. **"Timing of dialysis in acute kidney injury using routinely collected data and dynamic treatment regimes"**, *Critical Care*, 2022. \[[paper](https://ccforum.biomedcentral.com/articles/10.1186/s13054-022-04252-1)\]

-   Morzywołek, P., Steen, J., Van Biesen, W., Decruyenaere, J., Vansteelandt, S. **"On estimation and cross-validation of dynamic treatment regimes with competing risks"**, *Statistics in Medicine*, 2022. \[[paper](https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.9568)\] \[[arxiv](https://arxiv.org/abs/2109.00396)\] \[[code](https://github.com/pmorzywolek/comprisksDTR)\]

## 2021

-   Vanmassenhove J., Steen, J., Vansteelandt, S., Morzywołek, P., Hoste, E., Decruyenaere, J., Benoit, D., Van Biesen, W. **"The importance of the urinary output criterion for the detection and prognostic meaning of AKI"**, *Scientific Reports*, 2021. \[[paper](https://www.nature.com/articles/s41598-021-90646-0)\]

## Theses

-   [PhD Thesis](https://biblio.ugent.be/publication/01H3EW84JAFS8RHX17SY41M5M3): **"Causal inference methods to optimize clinical decision-making in treatment initiation based on routinely collected data"**, Ghent University, 2023.

-   [Master Thesis](https://ethz.ch/content/dam/ethz/special-interest/mtec/chair-of-entrepreneurial-risks-dam/documents/dissertation/master%20thesis/Master_Thesis_%20Morzywolek.pdf): **"Non-parametric methods for estimation of Hawkes process for high-frequency financial data"**, ETH Zurich, 2015.

-   [Bachelor Thesis](../RandomTrees-BachelorThesis.pdf): **"Random trees: Convergence of discrete random trees to the continuum random tree"**, ETH Zurich, 2013.
